theme: jekyll-theme-architect
title: Jason Guan's Website
description: 
  Greetings and welcome to my page! My name is Jiaxiong Guan but I also go by Jason!
  I'm a CS student at CUNY Hunter College looking to pursue data science.
  I hope you enjoy your stay!